<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-INQUNRP" ignored="0" name="Dummy test" tests="6" failures="1" timestamp="2021-07-03T20:19:32 EDT" time="151.936" errors="0">
  <testcase name="getURL" time="0.174" classname="testingPackage.TitleAndURLTest"/>
  <testcase name="getText" time="0.018" classname="testingPackage.TitleAndURLTest"/>
  <testcase name="getTitle" time="0.708" classname="testingPackage.TitleAndURLTest"/>
  <testcase name="assertURLTest" time="0.031" classname="testingPackage.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.facebook.com/] but found [https://www.facebook.com1/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [https://www.facebook.com1/]
at testingPackage.LoginTest.assertURLTest(LoginTest.java:25)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- assertURLTest -->
  <testcase name="skiipTitleTest" time="0.012" classname="testingPackage.LoginTest">
    <skipped/>
  </testcase> <!-- skiipTitleTest -->
  <testcase name="loginTest" time="1.216" classname="testingPackage.LoginTest"/>
</testsuite> <!-- Dummy test -->
