<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-INQUNRP" ignored="0" name="login test" tests="6" failures="1" timestamp="2021-07-03T20:46:46 EDT" time="95.617" errors="0">
  <testcase name="getTitle" time="0.092" classname="testingPackage.TitleAndURLTest"/>
  <testcase name="getURL" time="0.016" classname="testingPackage.TitleAndURLTest"/>
  <testcase name="getText" time="0.01" classname="testingPackage.TitleAndURLTest"/>
  <testcase name="assertURLTest" time="0.056" classname="testingPackage.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.facebook.com/dev] but found [https://www.facebook.com1/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/dev] but found [https://www.facebook.com1/]
at testingPackage.LoginTest.assertURLTest(LoginTest.java:25)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- assertURLTest -->
  <testcase name="loginTest" time="0.438" classname="testingPackage.LoginTest"/>
  <testcase name="skiipTitleTest" time="0.008" classname="testingPackage.LoginTest">
    <skipped/>
  </testcase> <!-- skiipTitleTest -->
</testsuite> <!-- login test -->
